import Banner from './components/Banner';
import Header from './components/Header';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'BG-LAB',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<head />
			<body className='bg-slate-800 text-gray-300'>{children}</body>
		</html>
	);
}
